### ISSUE TITLE
WriteDiskItem.findValue() cannot handle fso_attributes.csv

### ISSUE THREAD

**Issue by denisri** [brainvisa/axon#1]
---

Author Name: **Riviere, Denis** (@denisri)
Original Redmine Issue: 11166, https://bioproj.extra.cea.fr/redmine/issues/11166
Original Date: 2014-09-29
Original Assignee: Riviere, Denis

---

More precisely it cannot generate a DiskItem which would require creating a fso_attributes.csv file, ie hierarchy attributes which cannot be stored in the file name.

This means wdi.findValue(item, requiredAttributes={'_database': other_db}) will fail if item has such attributes (acquisition_date, time_point etc)

As a consequence, the copydata process does not work for such items.

**Comment by sapetnioc** [comment]
Do you think someone is going to work on that one day ?
Speak if you think I should not close this issue.
