### ISSUE TITLE
Custom sqliteFileName should be stored per user

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#11]
Currently, a custom sqliteFileName is stored in `database_settings.minf` and is shared among all BrainVISA clients using this database.
This can lead to database corruption, when the sqlite file is stored on a network filesystem without file locking support (e.g. NFS). A workaround to this problem is to use a local sqlite file for each client (on a local filesystem), but the fact that the path to this file is shared among all clients means that all people using this database must use the exact same local path.
Ideally a setting should be available for each client to override the sqliteFileName stored in `database_settings.minf`. That setting could be stored in `~/.brainvisa/options.minf`.

**Comment by sapetnioc** [comment]
Do you think someone is going to work on that sometime ?
Speak if you don't want me to close this issue.
