### ISSUE TITLE
ExecutionNode.setHidden shadows Process.setHidden

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#15]
The new method introduced in https://github.com/brainvisa/axon/commit/709445f4412159f1912779679c29c588365e9794, `ExecutionNode.setHidden`, shadows `Process.setHidden`, which has the same name but a different prototype and purpose. This method is used in DISCO to hide irrelevant parameters in sub-processes of a pipeline (e.g. [deformation_disco_dartel_pipeline.py, line 56](https://bioproj.extra.cea.fr/redmine/projects/brainvisa-disco/repository/revisions/master/entry/brainvisa/toolboxes/disco/processes/Deformation/deformation_disco_dartel_pipeline.py#L56)).

Previously, `Process.setHidden` was accessible on a `ProcessExecutionNode` via `ProcessExecutionNode.__getattr__`. Now I am not sure how to access it without using private variables (e.g. `eNode._parameterized.setHidden`). 

I see two ways of getting out of this situation:

1. Renaming the new method `ExecutionNode.setHidden`

2. Exposing `_parameterized` as a read-only property, so users can call `eNode.parameterized.setHidden`.

My preference goes for renaming `ExecutionNode.setHidden`, what do you think @nsouedet ?

**Comment by denisri** [comment]
Probably both...
We use `_parameterized` quite everyday, which clearly shows that there is a flaw, and a need to access the underlying process in a public way. Thus the read-only proprerty `parameterized`seems a good idea.
Then having different names for methods doing different things is probably better also (but in this case it's the older `Parameterized.setHidden()` which would be better named as `setHiddenParameters()` (or `set_hidden_parameters()`), I don't know if it is used very often or in code which cannot be changed (from external toolboxes).

**Comment by ylep** [comment]
I agree that the older `Process.setHidden` could have a better name, but we should also maintain backward compatibility. Renaming it would also be inconsistent with `setVisible`, `setOptional`... until we rename them all.

Regardless if we rename `setHidden`, I will do the following:
- introduce `ExecutionNode.parameterized` as a read-only property in `master` and `integration`
- change DISCO to use the new accessor

**Comment by denisri** [comment]
This looks OK for me.

**Comment by ylep** [comment]
Pushed the fix to Axon and to DISCO. I will now open a PR to rename `ExecutionNode.setHidden`, to avoid future confusion between the two methods.
