### ISSUE TITLE
neuroConfig parses sys.argv unconditionally

### ISSUE THREAD

**Issue by denisri** [brainvisa/axon#2]
---

Author Name: **Riviere, Denis** (@denisri)
Original Redmine Issue: 16156, https://bioproj.extra.cea.fr/redmine/issues/16156
Original Date: 2017-02-03

---

When importing neuroConfig, the sys.argv parser is used unconditionally. This is not a good thing: when using brainvisa as a library, options parsing should not be done, or in any case not here.
Some modules (brainvisa.axon) already cope with this problem by temporarily replacing sys.argv, which is obviously not a good solution...

**Comment by sapetnioc** [comment]
Do you think someone is going to work on that sometime ?
Speak if you don't want me to close this issue.
