### ISSUE TITLE
The iteration dialog should be window-modal, not application-modal

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#25]
When clicking *Iteration* in a process, the resulting dialog is application-modal (it blocks you from interacting with any other BrainVISA window).  It should be window-modal only (block you from interacting from the parent process window, but let you interact with the rest of BrainVISA).

This would enable e.g. copy-pasting parameters from a different BrainVISA process into the Iteration window.

**Comment by denisri** [comment]
It even does not have to be modal at all when open from the main process selection window...
