### ISSUE TITLE
Parallel iteration over importers seems to deadlock

### ISSUE THREAD

**Issue by denisri** [brainvisa/axon#3]
---

Author Name: **Souedet, Nicolas** (@nsouedet)
Original Redmine Issue: 17509, https://bioproj.extra.cea.fr/redmine/issues/17509
Original Date: 2017-10-24

---

I had this crash on primatologist, but I think it is a more general issue.
Must we disable parallel run for iterations over importer ?

**Comment by sapetnioc** [comment]
Do you think someone is going to work on that sometime ?
Speak if you don't want me to close this issue.

**Comment by denisri** [comment]
They don't seem to deadlock or crash any longer...
