### ISSUE TITLE
Axon tests should run isolated from the user's HOME

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#33]
During axon tests, the configuration files from the user’s `HOME` directory are read (e.g. databases are initialized). Tests should run isolated, and not see the user's `HOME` at all.

**Comment by denisri** [comment]
That's true. We can either change the $HOME variable during tests, or use a specific user profile in axon (brainvisa -u something). The former is probably safer.

**Comment by sapetnioc** [comment]
Is it still necessary with casa-distro ?

**Comment by denisri** [comment]
Let's say this is done by casa-distro, if we remove the (new) symlinks to the host ~/.branvisa (which is actually true in the current test environments we have setup).
