### ISSUE TITLE
Remove the long-obsolete BrainVISA server for remote databases

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#37]
There is some long-obsolete code in BrainVISA that implements remote access to databases based on Pyro (notably in the directory https://github.com/brainvisa/axon/tree/bf42dbddad0fbad5b67046fa5c8e329ea421f474/python/brainvisa/remote).

Considering that we want to remove the dependency on Pyro, we should get rid of this code that is probably not used by anyone for a long time.

Any objection from the release team @brainvisa/release ?

**Comment by denisri** [comment]
I have no memory of this feature (!) So yes I completely agree with removing it.
