### ISSUE TITLE
Axon bugs when it encounters file names with characters outside of latin-1

### ISSUE THREAD

**Issue by denisri** [brainvisa/axon#4]
---

Author Name: **Leprince, Yann** (@ylep)
Original Redmine Issue: 18765, https://bioproj.extra.cea.fr/redmine/issues/18765
Original Date: 2018-08-27
Original Assignee: Cointepas, Yann

---

Strange bugs appear when Axon is confronted with file names that cannot be encoded using latin-1. For example, the Database browser will not show any remaining files after it encounters such a file.

Would it be enough to convert the whole Axon source from latin-1 to utf-8, or is there a deeper reason not to switch to utf-8?

Feel free to re-assign the bug to me, I can attempt the conversion later.

**Comment by ylep** [comment]
1e72743500457a4a890e2e75f8d609da961a646b should fix it. Thanks Denis!
