### ISSUE TITLE
The Viewer icon is not displayed consistently with parameters of type ListOf

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#5]
With parameters that have type `ListOf(ReadDiskItem(...))` or `ListOf(WriteDiskItem(...))`, the viewer icon (the eye on the right of the field) sometimes goes away when it should be present (the `Inspect Multiple Data` viewer, or another viewer process, is available).

I will try to provide more context if I do not manage to fix the bug…

**Comment by sapetnioc** [comment]
Do you think someone is going to work on that sometime ?
Speak if you don't want me to close this issue.
