### ISSUE TITLE
ProcessToSomaWorkflow convert all values to string but then the workflow fails when there is a boolean's list

### ISSUE THREAD

**Issue by clarafischer** [brainvisa/axon#51]
For the process 'SPM12CoregisterEandR_generic' one of the parameter is a list of boolean [False, False, False] for example and when send to soma_wokflow it is transformed to ['False', 'False', 'False'] so it fails. When I launch the same command than soma_workflow on the cluster without the quote it's ok. Can we make an exception for the list of Boolean to not convert the Boolean to string or am I not getting the whole picture ?

**Comment by denisri** [comment]
Confirmed. The problem seems to be upstream to Soma-workflow, in the workflow generation from Axon pipelines I think: when saving the workflow in brainvisa, the saved worklow contains lists of strings, not lists of bool or numbers.

**Comment by denisri** [comment]
Well, non-string arguments are not really well supported in soma-workflow. All used to be converted to strings, but this is ambiguous. There were special cases in SWF for numbers and `None`, but bool was apparently not handled.
I can fix it either by trying to handle `'True' `and `'False'` strings like `'None'` was (I have to find where) in SWF, but this way there will be no way to distinguish a bool value from the `"True"` string (as for `None` and numbers).

A better solution would be to support non-str values inside SWF, and modify axon to use them. But jobs schedulers would anyway have to convert things to strings when they are commandline arguments, so the ambiguity will remain at lower level (but it's still better in my opinion). I can fix it in the local scheduler, and try to change other schedulers, but cannot test all of them right now.

**Comment by denisri** [comment]
I have pushed an experimental fix, but you have to test, and also test that SWF otherwise still works in all situations...

**Comment by sapetnioc** [comment]
Can this issue be closed ?

**Comment by denisri** [comment]
Let's say yes because there has been a fix, but unconfirmed. We'll reopen if needed.
