### ISSUE TITLE
Exception: <undefined> is not a valid value for data type Unicode

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#64]
**Describe the bug**

These messages seem to appear the first time a Capsul-based process is opened in Axon:
```
Exception: <undefined> is not a valid value for data type Unicode
Exception: <undefined> is not a valid value for data type Unicode
Exception: <undefined> is not a valid value for data type Unicode
Exception: <undefined> is not a valid value for data type Unicode
```

**To Reproduce**
1. Open a fresh instance of `brainvisa`
2. Open the Morphologist 2021 pipeline, or a process of the (new) `highres-cortex` toolbox

**Environment:**
 - Engine: Singularity
 - Version of BrainVISA: 5.1 branch
 - For local builds, version of the casa-dev image: `casa-dev-5.3-14.sif`

**Additional context**
These messages seem harmless, but they pollute the log and may scare users into thinking something is wrong.

**Comment by denisri** [comment]
Actually this exception print is in axon/capsul matlab config sync and can easily be removed. I'm doing that.
