### ISSUE TITLE
AnaLabelVolumeEditor fails to save new changes after the first save

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#80]
In BrainVISA 5.1.1, AnaLabelVolumeEditor fails to save new changes after the first save, because `finalgraph.data/roi_Volume.nii` is not overwritten by subsequent saves:

https://github.com/brainvisa/axon/blob/8b709cfeccdc0b5722f78d9bd5d8c57be31da2c3/brainvisa/toolboxes/tools/processes/roi/AnaLabelVolumeEditor.py#L147-L150

It seems that AimsGraphConvert fails to check for successful writing of the output graph:

https://github.com/brainvisa/aims-free/blob/v5.1.1/aimsdata/src/AimsGraphConvert/graphConvert.cc#L660-L672

**Comment by denisri** [comment]
Well, it's actually `AimsGraphConvert` which doesn't overwrite existing files in the .data directory. There is probably a force option which is missing. I'm looking at it.
